version: 2

registries:
  composer-asset-packagist:
    type: composer-repository
    url: https://asset-packagist.org

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"    

- package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:00"
    labels:
      - "dependencies"
      - "infrastructure"
